version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    networks:
      - app-network

  express-app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
